POST http://127.0.0.1:8000/api/v1/test/

POST http://127.0.0.1:8000/api/v1/merchant HTTP/1.1
content-type: application/json

{
  "legal_name": "Legal Name",
  "description": "Description of merchant",
  "address": {
    "address_line_1": "123 Main St",
    "address_line_2": "",
    "city": "New York",
    "state": "NY",
    "postal_code": "10001",
    "country": "US"
  },
  "users": [
    {
        "first_name": "John",
        "middle_name": "",
        "last_name": "Doe",
        "position": "Owner",
        "email": "doe@john.com",
        "phone": "123-456-7890",
        "is_contact_person": true,
        "address": {
            "address_line_1": "123 Main St",
            "address_line_2": "",
            "city": "New York",
            "state": "NY",
            "postal_code": "10001",
            "country": "US"
        },
        "role": "admin"
    }
  ]
}

// Verify activation token
GET http://127.0.0.1:8000/api/v1/activate/673aca25f509e090ffabc76055bdb5a3 HTTP/1.1

// Set password
post http://127.0.0.1:8000/api/v1/set_password HTTP/1.1
content-type: application/json

{
    "password": "gigabiga2022!~",
    "secret":  "673aca25f509e090ffabc76055bdb5a3"
}

// Sign in
POST http://127.0.0.1:8000/api/v1/sign_in/ HTTP/1.1
content-type: application/json

{
    "email": "giga.songulashvili@gmail.com",
    "password": "1234qwer"
}

// Sign out
POST http://127.0.0.1:8000/api/v1/sign_out/ HTTP/1.1
Authorization: Bearer  


// Authorize merchant
get http://127.0.0.1:8000/api/v1/merchant http/1.1
authorization: bearer 6e8708aa29fa1748734cd94720fb807c 

// Create branch
POST http://127.0.0.1:8000/api/v1/branch HTTP/1.1
Authorization: Bearer e6283f01825bf7c09f050e9912898d7b
content-type: application/json

{
  "branch_name": "My Branch Name",
  "address": {
		"address_line_1": "address_line_1",
		"address_line_2": "address_line_2",
		"city": "city",
		"state": "state",
		"postal_code": "postal_code",
		"country": "country"
	}
}

// Fetch branch
GET http://127.0.0.1:8000/api/v1/branch/9 HTTP/1.1
Authorization: Bearer 22fdbb33e0dc51f1bf7af4620016a753

// Delete branch
DELETE http://127.0.0.1:8000/api/v1/branch/9 HTTP/1.1
Authorization: Bearer e6283f01825bf7c09f050e9912898d7b

// Search music
post http://127.0.0.1:8000/api/v1/search_music HTTP/1.1
authorization: bearer e1463439b97decebab48d9d7287f2354
content-type: application/json

{
  "query": "metallica die die die"
}

// Create playlist
POST http://127.0.0.1:8000/api/v1/playlist HTTP/1.1
authorization: bearer 6e8708aa29fa1748734cd94720fb807c
content-type: application/json

{
    "name": "Summer Playlist 1",
    "branch_id": 1
}

// Update playlist
PUT http://127.0.0.1:8000/api/v1/playlist HTTP/1.1
authorization: bearer 6e8708aa29fa1748734cd94720fb807c
content-type: application/json
{
    "id": 8,
    "name": "Tazooooo's Playlist",
    "branch_id": 1
}

// Delete playlist
DELETE http://127.0.0.1:8000/api/v1/playlist/8 HTTP/1.1
authorization: bearer 6e8708aa29fa1748734cd94720fb807c
content-type: application/json

// Add song to playlist
POST http://127.0.0.1:8000/api/v1/playlist_member HTTP/1.1
authorization: bearer 6e8708aa29fa1748734cd94720fb807c
content-type: application/json

{
    "playlist_id": 9,
    "track_id": 599
}

// Get playlist members
GET http://127.0.0.1:8000/api/v1/playlist/9 HTTP/1.1
authorization: bearer 6e8708aa29fa1748734cd94720fb807c
content-type: application/json

// Delete playlist member
DELETE http://127.0.0.1:8000/api/v1/playlist_member/1 HTTP/1.1
authorization: bearer 6e8708aa29fa1748734cd94720fb807c
content-type: application/json

// Fetch all branches
GET http://127.0.0.1:8000/api/v1/all_branches HTTP/1.1
authorization: bearer 6e8708aa29fa1748734cd94720fb807c
content-type: application/json
